---
title: "testfile"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Core Tidyverse
library(tidyverse)
library(glue)
library(forcats)

# Time Series
library(timetk)
library(tidyquant)
library(tibbletime)

# Visualization
library(cowplot)

# Preprocessing
library(recipes)

# Sampling / Accuracy
library(rsample)
library(yardstick) 

# Modeling
library(keras)
library(tfruns)

library(data.table)
library(magrittr)
```




```{r cars}
data <- fread("schiptweecsv.csv")

data[,AISTrajectPositionTimeStamp:= AISTrajectPositionTimeStamp %>% as.POSIXct]

data[,AISTrajectPositionTimeStamp_num:= AISTrajectPositionTimeStamp %>% as.numeric]
data <- data[AISTrajectPositionTimeStamp %>% order]

data <- data %>% tk_tbl() 

data


```



```{r pressure, echo=FALSE}
p1 <- data %>%
    ggplot(aes(AISTrajectPositionTimeStamp, AISTrajectPositionLongitude, AISTrajectPositionLatitude)) +
    geom_point(color = palette_light()[[1]], alpha = 0.5) +
    theme_tq() +
    labs(
        title = " (Full Data Set)"
    )

p2 <- data %>%
    
      ggplot(aes(AISTrajectPositionTimeStamp, AISTrajectPositionLongitude, AISTrajectPositionLatitude)) +
    geom_line(color = palette_light()[[1]], alpha = 0.5) +
    geom_point(color = palette_light()[[1]]) +
    geom_smooth(method = "loess", span = 0.2, se = FALSE) +
    theme_tq() +
    labs(
        title = "1749 to 1759 (Zoomed In To Show Changes over the Year)",
        caption = "datasets::sunspot.month"
    )

p_title <- ggdraw() + 
  draw_label("Sunspots", size = 18, fontface = "bold", 
             colour = palette_light()[[1]])

plot_grid(p_title, p1, p2, ncol = 1, rel_heights = c(0.1, 1, 1))
```

